### ISSUE TITLE
bqckup -v or bqckup --version not working

### ISSUE THREAD

**Issue by navotera** [bqckup/bqckup#32]
output nya salah. 
/tmp/_MEIUtvlcC/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.17) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
Usage: bqckup [OPTIONS] COMMAND [ARGS]...
Try 'bqckup --help' for help.
+- Error --------------------------------------------------------------------------------------------------------------+
| No such option: -v

Mestinya list of command yang muncul

**Comment by thisnugroho** [comment]
saat ini untuk cek versi jalankan command ini:

```shell
bqckup get-information
```
