### ISSUE TITLE
use bqckup applicaton in multiple server but same s3 bucket

### ISSUE THREAD

**Issue by navotera** [bqckup/bqckup#35]
seems like there is a bug, if the multiple server use the same bucket it will create the same directory : bqckup in the s3 bucket and it will overwrite the configuration (config.yml) on previous configuration. 

The suggestion should be : 
- Directory should be bqckup_ip4

**Comment by thisnugroho** [comment]
Sebenarnya sudah ada settingan untuk nama folder di [bcqkup.cnf](https://github.com/bqckup/bqckup/blob/1x/bqckup.cnf.example), tetapi mungkin sebagai improvement bisa ditambahkan IP terhadap server tersebut sebagai pembeda
