### ISSUE TITLE
Summary all and each domain and history

### ISSUE THREAD

**Issue by thisnugroho** [bqckup/bqckup#49]
Summary Include:
- Last backup datetime
- Last backup file size and name
- Total size of a bqckup (Database and Files)
- Total files
- Storage Name
- Schedule (daily | weekly | monthly)
- Next Backup (datetime)
- Local Backup

Commands:
```shell
bqckup summary --site domain1.com
bqckup summary
```

```shell
bqckup history --site domain1.com
bqckup history
```

**Comment by navotera** [comment]
History include : 
- backup name : abc (weekly)
- last backup date : 
- last database file size : 
- last file file size : 
- status (success/failed) 
- time consume
