### ISSUE TITLE
Improve CPU Usage

### ISSUE THREAD

**Issue by thisnugroho** [bqckup/bqckup#72]
Perlu di check kenapa ini menspawn banyak sekali bqckup ,seharusnya 1x aja

![CleanShot 2024-08-31 at 8  34 22](https://github.com/user-attachments/assets/877c0771-3d4b-452c-9fb4-db2b5c29db47)

**Comment by rejarevaldy** [comment]
# Overview
Masalah ini disebabkan oleh proses upload yang menggunakan fungsi thread yang disediakan oleh Boto S3.

`classes/s3.py`
```python
config = TransferConfig(
    multipart_threshold=1024 * 25,
    max_concurrency=10,
    multipart_chunksize=1024 * 25,
    use_threads=True,
)
```

Berikut perbandingan antara menggunakan thread dan tidak:

### `use_threads=True`
![Upload Menggunakan Thread](https://github.com/user-attachments/assets/a7394c4d-f68f-4dad-9b42-f7b31c24a73d)

### `use_threads=False`
![Upload Tanpa Thread](https://github.com/user-attachments/assets/05e45bdf-174f-47cd-8138-0d46a8557b7c)

**Referensi:**
[Boto3 S3 Upload Documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html)
